# -*- coding: utf-8 -*-
"""Whatsapp Chat Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZ8EHAUpf_Mn9eoW0JR3NSWE6vz5kuoH
"""

import pandas as pd
import numpy as np
import re
import nltk
nltk.download('vader_lexicon')
import matplotlib.pyplot as plt 
from PIL import Image
from collections import Counter
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
from nltk.sentiment.vader import SentimentIntensityAnalyzer

conversation = 'WhatsApp Chat.txt'

def date_time(s):
    pattern = r'^([0-9]+)/([0-9]+)/([0-9]+),([0-9]+)[ ]?(AM|PM|am|pm)?-'
    result = re.match(pattern, s)
    if result:
        return True
    return False

def find_author(s):
    s = s.split(":")
    if len(s) == 2:
        return True
    else:
        return False

def messages(line):
    splitline = line.split(' - ')
    dateTime = splitline[0]

    date, time = dateTime.split(",")

    message = " ".join(splitline[1:])

    if find_author(message):
        splitmessage = message.split(": ")
        author = splitmessage[0]
        message = " ".join(splitmessage[1:])
    else:
        author = None

    return date, time, author, message

data = []

conversation = 'WhatsApp Chat.txt'

with open(conversation, encoding="utf-8") as fp:
    fp.readline()

    messageBuffer = []
    date, time, author = None, None, None

    while True:
        line = fp.readline()
        if not line:
            break

        line = line.strip()

        if date_time(line):
            if len(messageBuffer) > 0:
                data.append([date, time, author, ' '.join(messageBuffer)])
                messageBuffer.clear()

                date, time, author, message = getDatapoint(line)
                messageBuffer.append(message)
            else:
                messageBuffer.append(line)

df = pd.DataFrame(data, columns=["Date", "Time", "Author", "Message"])

df["Date"] = pd.to_datetime(df['Date'])

data = df.dropna()


sentiments = SentimentIntensityAnalyzer()

data["Positive"] = [sentiments.polarity_scores(msg)["pos"] for msg in data["Message"]]
data["Negative"] = [sentiments.polarity_scores(msg)["neg"] for msg in data["Message"]]
data["Neutral"]  = [sentiments.polarity_scores(msg)["neu"] for msg in data["Message"]]

print (data.head(10))

x = sum(data["Positive"])
y = sum(data["Negative"])
z = sum(data["Neutral"])

def score(a, b, c):
    if (a > b) and (a > c):
        print("Positive")
    elif (b > a) and (b > c):
        print("Negative")
    else:
        print("Neutral")

score(x, y, z)